PL updates for Actions and changing Icon Square to Fill Icons
18F/cg-style pull request #285
Opened 2017-01-06 22:16 UTC by line47

General improvements to the PL.
Updating naming and for icon square to fill icons.
Separating the actions into sections (button, button outline, link)

2017-01-06 22:42 UTC, thisisdano requested changes
Couple quick changes, but otherwise OK to me

2017-01-06 22:42 UTC, thisisdano commented on docs/src/components/components/action/button/README.md
> +| `action-finish usa-button-finish`    | When to use |
`warning`, `primary`, `finish`, and `base` are the allowed values in the Action `style` prop. I think `cautious` can be nixed.

2017-01-06 22:42 UTC, thisisdano commented on docs/src/components/components/action/button-outline/README.md
> +| `action-finish`    | When to use |
`warning`, `primary`, `finish`, and `base` are the allowed values in the Action `style` prop. I think `cautious` can be nixed.

2017-01-06 22:42 UTC, thisisdano commented on docs/src/components/components/action/link/README.md
> +| `action-cautious`    | When to use |
`warning`, `primary`, `finish`, and `base` are the allowed values in the Action `style` prop. I think `cautious` can be nixed.

2017-01-06 22:42 UTC, thisisdano commented on docs/src/components/components/fill-icons/README.md
> +such as the `org` icon.
I rebuilt the org icon a while back and it's now OK

2017-01-06 22:42 UTC, thisisdano commented on docs/src/components/components/fill-icons/fill-icons.config.yml
> +title: Filll Icons
typo

2017-01-06 22:42 UTC, thisisdano commented on docs/src/components/components/icon-square/README.md
>  such as the `org` icon.
See previous. Org icon is now ok.

2017-01-09 14:39 UTC, line47 commented on docs/src/components/components/action/button/README.md
> +| `action-finish usa-button-finish`    | When to use |
Awesome, thanks!

2017-01-09 15:02 UTC, line47 commented on docs/src/components/components/action/button/README.md
> +| `action-finish usa-button-finish`    | When to use |
@thisisdano what do you think here?
The class `action-cautious` is being used for the disabled state of the buttons and links. I think this class needs to be updated to `action-disabled`.

2017-01-09 15:52 UTC, thisisdano commented on docs/src/components/components/action/button/README.md
> +| `action-finish usa-button-finish`    | When to use |
agree that `action-cautious` is confusing. `action-disabled` is far clearer.

2017-01-09 15:56 UTC, thisisdano commented on docs/src/components/components/action/button/README.md
> +| `action-finish usa-button-finish`    | When to use |
it looks like the `disabled` prop renders `usa-button-disabled` in the templates in addition to any `style` props passed

2017-01-09 16:01 UTC, line47 commented on docs/src/components/components/action/button/README.md
> +| `action-finish usa-button-finish`    | When to use |
I'll address that in a different PR. @thisisdano can you review this PR again?

2017-01-09 16:06 UTC, line47 commented
Adding [content guidelines](https://github.com/18F/cg-product/blob/master/ContentGuide.md) to the pattern library @brittag

2017-01-09 16:27 UTC, thisisdano approved these changes
lgtm

2017-01-09 16:46 UTC, merged